### PR TITLE
Changes to write buffer, add delete buffer, upgrade dependencies

### PR DESCRIPTION
**Pull request by grechaw**
This PR has a change to use SPARQL UPDATE for write buffering #48 
It implements a buffer for deletes #45 
#29 is complete with this PR too.

A second PR for Jena 2 + Java 1.7 is also ready.

### CODE REVIEW

**Comment by grechaw** [comment]
Hi @xquery  can you take a peek at this PR for sanity check?

**Comment by xquery** [comment]
generally +1, though now wondering how you set enhanced feature like marklogic perms on these triples ?

**Comment by grechaw** [comment]
Just what occurred to me last night.  I had seen that you have a particular task to review this stuff.

**Comment by grechaw** [comment]
In design of marklogic-jena, permissions and content are handled in separate calls.  Could be changed for the future, but for now that means changes to write buffer are not affected by permissions.

**Comment by grechaw** [comment]
@kkanthet I'd like to merge this PR.  Any concerns about changes to write and delete buffers?  I'll be adding threaded tests to estabilsh behavior here too.

**Pull request merged**
