### PR TITLE
Pull request for JenaDatabaseClient

### PR DESCRIPTION
**Pull request by MichalWozniakSmartlogic**
In this pull request we introduce two changes to JenaDatabaseClient that we found out 
necessary for our system. The changes have been tested as we use the forked version 
already in our system. Also, the changes preserve the current API of the client.

There changes are:
- an option to turn off the timer-based flushing mechanism ("periodicFlush = false", 
  we use this option in our system, the default remains "periodicFlush = true").
- closing client transaction when currentTransaction.rollback() fails (abort() method)

### CODE REVIEW

**Comment by grechaw** [comment]
Thank you for this PR!    The changes all make sense to me.  Is there any reason why there are so many commits in the PR?  I would prefer to merge this as one commit.

We also need to direct you to a contributor's agreement to accept changes into the repo.  Take a look here https://github.com/marklogic/marklogic-jena/blob/fba328bbebeec368979953a85e26bad02bc7d7a3/CONTRIBUTING.md and
I'll get in touch with my product manager.

**Comment by xquery** [comment]
looks good to me (and will rob some suggestions for marklogic-sesame)

**Comment by grechaw** [comment]
Hi @MichalWozniakSmartlogic , one thing to be aware of as well -- develop branch has been updated to use jena-3.  1.0-develop is still against jena-2

**Comment by MichalWozniakSmartlogic** [comment]
Thanks for your comments. There is no important reason for many commits. Thus, I created another "collapsed" pull-request: https://github.com/marklogic/marklogic-jena/pull/34/files. Please review that one. Also, thanks of letting us know on the jena-3. As for now, we use jena-2 in our product though.

**Comment by grechaw** [comment]
Great.  I'll test this and merge it to both branches, probably tomorrow.  @sbuxton will give me the goahead most likely.

**Comment by grechaw** [comment]
Pull #34 has superceded this, closing.

**Pull request closed without merging**
