### PR TITLE
Sonar recommendations, formatting, java client 3.0.4

### PR DESCRIPTION
**Pull request by grechaw**
Do not merge

This is a proposed new branch.  It updates versions, and incorporates some formatting updates and recommendations from sonar.  I have another PR coming that updates to jena 3 with an alternate commit.  This one retains Jena 2.

Once @xquery  and @kkanthet approve, I'll create the new branch with this commit (and subsequent recommendations from illustrious colleagues.

### CODE REVIEW

**Comment by grechaw** [comment]
@xquery gave me verbal goahead on these two PRs.  Kiran does this match your expectation of how we'll manage branch and dependencies for now?

**Comment by kkanthet** [comment]
Hi Charles,

Just to confirm, we will rename develop to 1.0-develop , master to 1.0-master —> will contain Jena2
Create 2.0-develop and 2.0-master —> Jena3
Right?

Than You,
Kiran

From: Charles Greer
Reply-To: marklogic/marklogic-jena
Date: Wednesday, January 20, 2016 at 9:52 AM
To: marklogic/marklogic-jena
Cc: Kiran Kantheti
Subject: Re: [marklogic-jena] Sonar recommendations, formatting, java client 3.0.4 (#31)

@xqueryhttps://github.com/xquery gave me verbal goahead on these two PRs. Kiran does this match your expectation of how we'll manage branch and dependencies for now?

**Comment by grechaw** [comment]
Hi @kkanthet , I'm more interested in 

(current commit in ) develop -> 1.0-develop  
master to 1.0-master  (not until next release - we don't have rationale to change master yet IMO)
—> will contain Jena2  yes

Create develop and master —> Jena3   (took out 2.0-, this is just the most recent develop)

**Comment by kkanthet** [comment]
Thank You Charles, I think that looks good.

From: Charles Greer
Reply-To: marklogic/marklogic-jena
Date: Wednesday, January 20, 2016 at 10:10 AM
To: marklogic/marklogic-jena
Cc: Kiran Kantheti
Subject: Re: [marklogic-jena] Sonar recommendations, formatting, java client 3.0.4 (#31)

Hi @kkanthethttps://github.com/kkanthet , I'm more interested in

(current commit in ) develop -> 1.0-develop

master to 1.0-master (not until next release - we don't have rationale to change master yet IMO)
—> will contain Jena2 yes

Create develop and master —> Jena3 (took out 2.0-, this is just the most recent develop)

**Comment by grechaw** [comment]
Merged by hand to new branch.

**Pull request closed without merging**
